imdb/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'
urlpatterns = [
    path('movies/', MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', MovieDetail.as_view(), name='MovieDetail'),
    path('movie/<int:movie_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/upload', MovieUpload.as_view(), name='MovieUpload'),
    path('movies/top_10/', TopView.as_view(), name='Top10MoviesList')
]

imdb/users/urls.py
from django.urls import path, include
from .views import *
import django.contrib.auth.urls
from django.contrib.auth.views import LogoutView, LoginView

app_name = 'users'
urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]

imdb/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUserModel(AbstractUser):
    pass

imdb/users/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):

    class Meta:
        model = MyUserModel
        fields = ('username', 'password1', 'password2')

imdb/users/views.py
from django.shortcuts import render

# registration views

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignUpForm

class RegisterView(CreateView):
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('core:MovieList')

imdb/users/templates/users/login.html
{% extends 'base.html' %}


{% block main %}

<h2>Login Page</h2>
<form method = "post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit" class="btn btn-primary"> submit </button>
</form>

{% endblock %}


{% block sidebar %}

{% endblock %}

imdb/users/templates/users/logout.html
{% extends 'base.html' %}

{% block main %}
<h3>You are now logged out from this Website</h3>
{% endblock %}


{% block sidebar %}
<p></p>
{% endblock %}

imdb/users/templates/users/signup.html
{% extends 'base.html' %}


{% block main %}
    <h1>Register for MyMDB</h1>
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
{% endblock %}


{% block sidebar %}

{% endblock %}