imdb/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'
urlpatterns = [
    path('movies/', MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', MovieDetail.as_view(), name='MovieDetail'),
    path('movie/<int:movie_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/upload', MovieUpload.as_view(), name='MovieUpload'),
    path('movies/top_10/', TopView.as_view(), name='Top10MoviesList')
]

imdb/core/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models.aggregates import Sum
from uuid import uuid4


def movie_directory_path_with_uuid(instance, filename):
#    return '%d/%d' % (instance.movid.id, uuid4()) test this above string formatting to see if this works.
    return '{}/{}'.format(instance.movie_id, uuid4())

# class MovieImageModel
class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(to='Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)




# creating a movie manager
class MovieManager(models.Manager):

    def all_with_related_person(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('actors', 'writers')
        return qs

    def all_score(self):
        qs = self.all_with_related_person()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_10_movies(self, limit):
        qs = Movie.objects.all().annotate(score=Sum('vote__value'))
        qs = qs.exclude(score=None)
        qs = qs.order_by('-score')
        qs = qs[:limit]
        return qs



class PersonManager(models.Manager):

    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed', 'writing_credits', 'role_set__movie')




class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')


    def __str__(self):
        if self.died:
            return '%s, %s %s-%s' % (self.last_name, self.first_name, str(self.born), str(self.died))
        return '%s, %s %s' % (self.last_name, self.first_name, str(self.born))




class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )
    director = models.ForeignKey(Person, related_name='directed',on_delete=models.SET_NULL, null=True, blank=True)
    writers = models.ManyToManyField(Person, related_name='writing_credits', blank=True)
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    runtime = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    website = models.URLField(blank=True)
    actors = models.ManyToManyField(
        Person,
        through='Role',
        related_name='acting_credits',
        blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')


    def __str__(self):
        return '%s, %d' % (self.title, self.year)



class Role(models.Model):

    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)


    class Meta:
        unique_together = ('movie', 'person', 'name')

    def __str__(self):
        return '%d %d %s' % (self.movie.id, self.person.id, self.name)



class VoteManager(models.Manager):

    def get_vote_or_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)



class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, 'Like'),
        (DOWN, 'Dislike'),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')


    def __str__(self):
        return '%s voted on %s' % (self.user, self.movie)

    def get_absolute_url(self):
        return reverse('core:MovieList')

imdb/core/forms.py
from django import forms
from .models import Movie
from .models import Vote, MovieImage
from django.contrib.auth import get_user_model
from django.conf import settings

class VoteForm(forms.ModelForm):
    # To prevent Users for voting for other users we must add more code to this form
    # Note when you set any field attribute disabled=True that particular field will not be able to post data
    user = forms.ModelChoiceField( queryset=get_user_model().objects.all(), widget=forms.HiddenInput)
    movie = forms.ModelChoiceField( queryset=Movie.objects.all(), widget=forms.HiddenInput)
    value = forms.ChoiceField(label='Vote', widget=forms.RadioSelect, choices=Vote.VALUE_CHOICES)


    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie')



class ImageForm(forms.ModelForm):

    user = forms.ModelChoiceField( widget=forms.HiddenInput, queryset=get_user_model().objects.all())
    movie = forms.ModelChoiceField( widget=forms.HiddenInput,  queryset=Movie.objects.all())

    class Meta:
        model = MovieImage
        fields = ('user', 'movie', 'image')

imdb/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Movie, Person, Vote, MovieImage
from django.views import View
from .forms import VoteForm, ImageForm
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
from django.core.exceptions import PermissionDenied

class MovieList(ListView):
    model = Movie
    paginate_by = 3

class MovieDetail(DetailView):

    model = Movie
    queryset = Movie.objects.all_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_blank_vote(movie=self.object, user=self.request.user)
            if vote.id:
                vote_form_url = reverse('core:UpdateVote', kwargs={'movie_id': self.object.id, 'pk': vote.id})
            else:
                vote_form_url = reverse('core:CreateVote', kwargs={'movie_id': self.object.id})
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url']  = vote_form_url
            image_form = ImageForm(initial={
                'user': self.request.user,
                'movie': Movie.objects.get(pk=self.object.id),
            })
            ctx['image_form'] = image_form
        return ctx




class PersonDetailView(DetailView):

    queryset = Person.objects.all_with_prefetch_movies()
    template_name = 'core/my_person_detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Indiviual Detail'
        return data


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm
    template_name = 'core/test.html'

    # this method below i believe is to fill the form with initial data
    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        movie_id = self.kwargs['movie_id']
        initial['movie'] = Movie.objects.get(pk=movie_id)
        return initial


    def form_invalid(self, form):
        print('form invalid')
        print(form.cleaned_data)
        return redirect(to=(reverse('core:MovieDetail', kwargs={'pk':self.kwargs['movie_id']})))

    def get_success_url(self):
        return reverse('core:MovieList')




class UpdateVote(LoginRequiredMixin, UpdateView):

    form_class = VoteForm
    template_name = ''
    queryset = Vote.objects.all()


    def get_object(self, queryset=None):
        vote = super().get_object(self.queryset)
        user = self.request.user
        movie = vote.movie
        if user != vote.user:
            raise PermissionDenied('cannot change antoher users vote')
        return vote

    def get_success_url(self):
        return reverse('core:MovieList')



class MovieUpload(LoginRequiredMixin, CreateView):

    form_class = ImageForm
    model = MovieImage
    movie_id = ''
    template_name = 'core/imageupload.html'

    def get_initial(self):
        initial = super(MovieUpload, self).get_initial()
        initial['user'] = self.request.user
        initial['movie'] = self.kwargs['movie_id']
        self.movie_id = self.kwargs['movie_id']
        return initial

    def form_invalid(self, form):
        print('inside form invalid')
        print(form.cleaned_data)
        return redirect(to='core:MovieList')

    def get_success_url(self):
        return reverse('core:MovieDetail', kwargs={'pk': self.movie_id})

class TopView(ListView):
    model = Movie
    queryset = Movie.objects.top_10_movies(10)
    template_name = 'core/top_10_movies.html'

imdb/core/templates/core/imageupload.html
{% extends 'base.html' %}


{% block main %}
<h2>did it work?</h2>
{% endblock %}

imdb/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title|title }} - {{ block.super }}
{% endblock %}



{% block main %}
<h1> {{ object|title }} </h1>
<p> {{ object.plot }} </p>

<div class="row">
    {% for i in object.movieimage_set.all %}
    <div class="col-md-6">
        <div class="thumbnail">
            <a href="#">
                <img src="{{ i.image.url }}" alt="Lights" style="width:100%; height:200px">
            </a>
        </div>
  </div>
    {% endfor %}
</div>

{% endblock %}

{% block sidebar %}
    <div>
        {% if vote_form %}
            <form method="post" action="{{vote_form_url}}">
                {% csrf_token %}
                {{ vote_form.as_p }}
                <button type="submit" class="btn btn-primary"> Vote </button>
            </form>
        {% else %}
            <p>Log in to Vote for this page</p>
        {% endif %}

        {% if image_form %}
            <h2>New Image Upload</h2>
            <form method = 'post' enctype="multipart/form-data" action="{% url 'core:MovieUpload' movie_id=object.id %}">
                {% csrf_token %}
                {{ image_form.as_p }}
                <button type = "submit" class='btn btn-primary'>Upload</button>
            </form>
        {% endif %}

    </div>

    <div>
        <h2>
            Score: {{ object.score|default_if_none:"No rating available" }}
        </h2>
    </div>

{% endblock %}

imdb/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block main %}
<h2> All Movies </h2>
<ul>
    {% for movie in object_list %}
    <li>
    <a href = '{% url "core:MovieDetail" pk=movie.id %}'>
             {{ movie|title  }}
        </a>
     </li>
    {% empty %}
        <li>No movies yet</li>
    {% endfor %}
</ul>

{% if is_paginated %}
<nav>
    <ul class = 'pagination'>
        <li class = 'page-item'>
            <a href = '{% url "core:MovieList" %}?page=1' class="page-link">First</a>
        </li>
        {% if page_obj.has_previous %}
        <li class = 'page-item'>
            <a href = '{% url "core:MovieList" %}?page={{page_obj.previous_page_number}}' class="page-link">{{page_obj.previous_page_number}}</a>
        </li>
        {% endif %}
        <li class="active page-item">
            <a href = '{% url "core:MovieList" %}?page={{page_obj.number}}' class="page-link">{{page_obj.number}}</a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href = '{% url "core:MovieList" %}?page={{page_obj.next_page_number}}' class="page-link">{{page_obj.next_page_number}}</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a href = '{% url "core:MovieList" %}?page=last' class="page-link">last</a>
        </li>
    </ul>
</nav>

{% endif %}


<p>using https?
{{ request.is_secure|yesno }}
</p>
{% endblock %}

imdb/core/templates/core/my_person_detail.html
{% extends 'base.html' %}

{% block title %} {{ title }}  {% endblock %}


{% block main %}
<h1> {{ object }} </h1>
<h2> Actor </h2>
<ul>
    {% for role in role_set.all %}
    <li>
        <a href="{% url 'core:MovieDetail' role.movie.id %}"> {{ role.movie }} </a>:
            {{ role.name }}
    </li>
    {% endfor %}
</ul>

<h2>  Writer </h2>
<ul>
    {% for movie in object.writing_credits.all %}
    <li>
        <a href="{% url 'core:MovieDetail' movie.id %}"> {{ movie }} </a>
    </li>
    {% endfor %}
</ul>


<h2> Director </h2>
<ul>
    {% for movie in objects.directed.all %}
    <li>
        <a href="{% url 'core:MovieDetail' movie.id %}"> {{ movie }} </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

{% block sidebar %}

{% endblock %}

imdb/core/templates/core/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ movie }}
{{ movie_id }}
</body>
</html>

imdb/core/templates/core/top_10_movies.html
{% extends 'base.html' %}

{% block title %}
    My Top 10
{% endblock %}

{% block main %}
    <h2>The Top 10 Movies Picks </h2>
    <ol class>
    {% for element in object_list %}
        <li><a href="{% url 'core:MovieDetail' pk=element.id %}">{{ element }} - score : {{ element.score }} </a></li>
    {% endfor %}
    </ol>
{% endblock %}

imdb/core/templates/core/vote.html
{% extends 'base.html' %}


{% block main %}

 {{user}}<br>

<form method="post" action="#">
    {{ form.as_p }}
    <button type="submit" value="submit" class="btn btn-primary"> submit </button>
</form>

{% endblock %}